
package login;

import JDBC.Jdbc;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author ushan tharuka
 */
public class login extends javax.swing.JFrame {

    Jdbc db = new Jdbc();
    
    public login() {
        initComponents();
        progressbar.setVisible(false);
        message_lbl.setVisible(false);
    }

    void close(){
        this.dispose();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        message_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in");

        jPanel1.setLayout(null);

        username_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_txtKeyPressed(evt);
            }
        });
        jPanel1.add(username_txt);
        username_txt.setBounds(210, 80, 260, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 80, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 130, 110, 40);

        password_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txtKeyPressed(evt);
            }
        });
        jPanel1.add(password_txt);
        password_txt.setBounds(210, 130, 260, 40);

        login_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn);
        login_btn.setBounds(210, 190, 160, 50);

        message_lbl.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        message_lbl.setForeground(new java.awt.Color(0, 0, 204));
        message_lbl.setText("WelCome");
        jPanel1.add(message_lbl);
        message_lbl.setBounds(30, 190, 130, 60);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Source Sans Pro Black", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hardware Shop");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 600, 64);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -10, 630, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        if(username_txt.getText().isEmpty() || password_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Username or password Empty...");
        }else{
            try {
                ResultSet r = db.getdata("SELECT password FROM users "
                    + "WHERE name='"+username_txt.getText()+"'");

                while(r.next()){
                    if(r.getString("password").equals(password_txt.getText())){

                        //progress bar
                        progressbar.setVisible(true);
                        message_lbl.setVisible(true);
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try{
                                    for(int i=progressbar.getMinimum();i<=progressbar.getMaximum();i++){
                                        progressbar.setValue(i);
                                        Thread.sleep(10);

                                        if(i==progressbar.getMaximum()){
                                            close();
                                            new dashbord.dashbord().setVisible(true);
                                            Thread.currentThread().stop();

                                        }
                                    }
                                }catch(Exception e){
                                    System.out.println(e);
                                }
                            }
                        }).start();

                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void username_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_txtKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            login();
        
        }
    }//GEN-LAST:event_username_txtKeyPressed

    private void password_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            login();
        
        }
    }//GEN-LAST:event_password_txtKeyPressed

    
    private void login(){                                          
        if(username_txt.getText().isEmpty() || password_txt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Username or password Empty...");
        }else{
            try {
                ResultSet r = db.getdata("SELECT password FROM users "
                    + "WHERE name='"+username_txt.getText()+"'");

                while(r.next()){
                    if(r.getString("password").equals(password_txt.getText())){

                        //progress bar
                        progressbar.setVisible(true);
                        message_lbl.setVisible(true);
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try{
                                    for(int i=progressbar.getMinimum();i<=progressbar.getMaximum();i++){
                                        progressbar.setValue(i);
                                        Thread.sleep(10);

                                        if(i==progressbar.getMaximum()){
                                            close();
                                            new dashbord.dashbord().setVisible(true);
                                            Thread.currentThread().stop();

                                        }
                                    }
                                }catch(Exception e){
                                    System.out.println(e);
                                }
                            }
                        }).start();

                    }
                }
            } catch (Exception e) {
            }
        }
    }                              
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel message_lbl;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
